import torch.nn as nn


class Discriminator(nn.Module):
    """A generic Discriminator, defining the latter half of the GAN structure.
    All Discriminators will take in a tensor of a given shape, and classify it as either
    real or fake (or rather, 'in training data' or 'generated by Generator').
    """

    def __init__(self, input_shape: tuple):
        super(Discriminator, self).__init__()
        self.input_shape = input_shape
