import torch
import torch.nn as nn
import torch.nn.functional as func

from Models.Discriminator import Discriminator


"""See https://github.com/salu133445/ismir2019tutorial/blob/main/musegan.ipynb for more info.
Slight modifications made to match the implementation to that described in the original MuseGAN appendix.
Additional modifications made such that the discriminator operates over single-track data."""


class LayerNorm(torch.nn.Module):
    """An implementation of Layer normalization that does not require size
    information. Copied from https://github.com/pytorch/pytorch/issues/1959."""
    def __init__(self, n_features, eps=1e-5, affine=True):
        super().__init__()
        self.n_features = n_features
        self.affine = affine
        self.eps = eps
        if self.affine:
            self.gamma = torch.nn.Parameter(torch.Tensor(n_features).uniform_())
            self.beta = torch.nn.Parameter(torch.zeros(n_features))

    def forward(self, x):
        shape = [-1] + [1] * (x.dim() - 1)
        mean = x.view(x.size(0), -1).mean(1).view(*shape)
        std = x.view(x.size(0), -1).std(1).view(*shape)
        y = (x - mean) / (std + self.eps)
        if self.affine:
            shape = [1, -1] + [1] * (x.dim() - 2)
            y = self.gamma.view(*shape) * y + self.beta.view(*shape)
        return y


class DiscriminatorBlock(torch.nn.Module):
    def __init__(self, in_dim, out_dim, kernel, stride):
        super().__init__()
        self.transconv = torch.nn.Conv3d(in_dim, out_dim, kernel, stride)
        self.layernorm = LayerNorm(out_dim)

    def forward(self, x):
        x = self.transconv(x)
        x = self.layernorm(x)
        return torch.nn.functional.leaky_relu(x)


n_measures = 4
measure_resolution = 96
n_pitches = 84


class MuseGANDiscriminator(Discriminator):
    """A convolutional neural network (CNN) based discriminator. The
    discriminator takes as input either a real sample (in the training data) or
    a fake sample (generated by the generator) and outputs a scalar indicating
    its authentity.
    """
    def __init__(self):
        super().__init__(d_model=n_pitches)
        self.conv0 = DiscriminatorBlock(1, 128, (2, 1, 1), (1, 1, 1))
        self.conv1 = DiscriminatorBlock(128, 128, (3, 1, 1), (1, 1, 1))
        self.conv2 = DiscriminatorBlock(128, 128, (1, 1, 12), (1, 1, 12))
        self.conv3 = DiscriminatorBlock(128, 128, (1, 1, 7), (1, 1, 7))
        self.conv4 = DiscriminatorBlock(128, 128, (1, 2, 1), (1, 2, 1))
        self.conv5 = DiscriminatorBlock(128, 128, (1, 2, 1), (1, 2, 1))
        self.conv6 = DiscriminatorBlock(128, 256, (1, 4, 1), (1, 2, 1))
        self.conv7 = DiscriminatorBlock(256, 512, (1, 3, 1), (1, 2, 1))
        self.dense0 = torch.nn.Linear(2816, 1)

    def forward(self, x):
        x = x.view(-1, 1, n_measures, measure_resolution, n_pitches)
        x = self.conv0(x)
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.conv3(x)
        x = self.conv4(x)
        x = self.conv5(x)
        x = self.conv6(x)
        x = x.view(-1, 2816)
        x = self.dense0(x)
        x = torch.sigmoid(x)
        return x
